# Generated by Django 3.0.8 on 2021-06-07 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Загальна цена')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('description', models.TextField(null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('for_main_page', models.BooleanField(default=False, verbose_name='Показувати на головній')),
                ('conditioner_type', models.CharField(blank=True, choices=[('Настінні спліт-системи', 'Настінні спліт-системи'), ('Мультиспліт-системи', 'Мультиспліт-системи'), ('Мобільні кондиціонери', 'Мобільні кондиціонери'), ('Кондиціонери на стелю', 'Кондиціонери на стелю'), ('Касетні кондиціонери', 'Касетні кондиціонери'), ('Канальні кондиціонери', 'Канальні кондиціонери')], max_length=255, null=True, verbose_name='Тип кондиціонера')),
                ('brand', models.CharField(choices=[('AUX', 'AUX'), ('Cooper&Hunter', 'Cooper&Hunter'), ('Daikin', 'Daikin'), ('Gree', 'Gree'), ('Hitachi', 'Hitachi'), ('Leberg', 'Leberg'), ('LG', 'LG'), ('Mitsubishi Electric', 'Mitsubishi Electric'), ('Mitsubishi Heavy', 'Mitsubishi Heavy'), ('Neoclima', 'Neoclima'), ('Olmo', 'Olmo'), ('Panasonic', 'Panasonic'), ('Samsung', 'Samsung'), ('Smartway', 'Smartway'), ('Toshiba', 'Toshiba')], max_length=255, verbose_name='Бренд')),
                ('cold_efficiency', models.CharField(max_length=255, verbose_name='Продуктивність холод, кВт')),
                ('warm_efficiency', models.CharField(max_length=255, verbose_name='Продуктивність тепло, кВт')),
                ('cold_watt_consumption', models.CharField(max_length=255, verbose_name='Споживання потужності холод, кВт')),
                ('warm_watt_consumption', models.CharField(max_length=255, verbose_name='Споживання потужності тепло, кВт')),
                ('recommended_area', models.CharField(choices=[('до 20', 'до 20'), ('до 25', 'до 25'), ('до 35', 'до 35'), ('до 45', 'до 45'), ('до 50', 'до 50'), ('до 60', 'до 60'), ('до 70', 'до 70'), ('> 70', '> 70')], max_length=255, verbose_name='Рекомендована площа приміщення, м²')),
                ('invertor', models.CharField(choices=[('Так', 'Так'), ('Ні', 'Ні')], max_length=255, verbose_name='Інвертор')),
                ('invertor_power', models.CharField(blank=True, choices=[('7 BTU', '7 BTU'), ('9 BTU', '9 BTU'), ('12 BTU', '12 BTU'), ('18 BTU', '18 BTU'), ('24 BTU', '24 BTU')], max_length=255, null=True, verbose_name='Потужність інвертора')),
                ('energy_efficiency', models.CharField(max_length=255, verbose_name='Енергоефективність EER/C.O.P.,кВт/кВт')),
                ('liquid_tube_diameter', models.CharField(max_length=255, verbose_name='Діаметер рідинної труби, мм')),
                ('gas_tube_diameter', models.CharField(max_length=255, verbose_name='Діаметер газової труби, мм')),
                ('max_magistral_length', models.PositiveIntegerField(verbose_name='Максимальна довжина магістралі, м')),
                ('max_magistral_hight_variation', models.PositiveIntegerField(verbose_name='Максимальний перепад висоти магістралі, м')),
                ('cold_work_temratures', models.CharField(max_length=255, verbose_name='Діапазон роботи на холод,°C')),
                ('warm_work_temratures', models.CharField(max_length=255, verbose_name='Діапазон роботи на тепло,°C')),
                ('freon', models.CharField(max_length=255, verbose_name='Фреон')),
                ('energy_source', models.CharField(max_length=255, verbose_name='Джерело живлення')),
                ('warrant', models.CharField(max_length=255, verbose_name='Гарантія')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Виробник')),
                ('dims', models.CharField(max_length=255, verbose_name='Габаритні розміри, мм')),
                ('weight', models.CharField(max_length=255, verbose_name='Вага, кг')),
                ('noise', models.CharField(max_length=255, verbose_name='Рівень шуму,дБ(А)(мин/ср/макс)')),
                ('air_consumption', models.CharField(max_length=255, verbose_name='Споживання повітря, м³/год. ')),
                ('filter', models.CharField(max_length=255, verbose_name='Фільтр')),
                ('color', models.CharField(max_length=255, verbose_name='Колір')),
                ('outer_dims', models.CharField(max_length=255, verbose_name='Габаритні розміри, мм')),
                ('outer_weight', models.CharField(max_length=255, verbose_name='Вага, кг')),
                ('outer_noise', models.CharField(max_length=255, verbose_name='Рівень шуму,дБ(А)(мин/ср/макс)')),
                ('outer_distance_between_bases', models.CharField(max_length=255, verbose_name='Відстань між лапами, мм')),
                ('compressor_type', models.CharField(max_length=255, verbose_name='Тип компресора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functions.Category', verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адреса')),
                ('status', models.CharField(choices=[('new', 'Нове замовлення'), ('in_progress', 'Замовлення обробляється'), ('is_ready', 'Замовлення готове'), ('completed', 'Замовлення виконане')], default='new', max_length=100, verbose_name='Статус замовлення')),
                ('buying_type', models.CharField(choices=[('self', 'Самовивіз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='Тип замовлення')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар до замовлення')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата створення замовлення')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отримання замовлення')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_functions.Cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='main_functions.Customer', verbose_name='Покупець')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='main_functions.Order', verbose_name='Замовлення покупця'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Загальна ціна')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='main_functions.Cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functions.Product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functions.Customer', verbose_name='Покупець')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_functions.Customer', verbose_name='Власник'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='main_functions.CartProduct'),
        ),
    ]
