# Generated by Django 3.0.8 on 2021-05-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=100, verbose_name='Ключ характеристики')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Назва характеристики')),
                ('postfix_for_value', models.CharField(blank=True, help_text='Для деяких характеристик до значення можна додати постфікс', max_length=20, null=True, verbose_name='Постфікс для значення')),
                ('user_in_filter', models.BooleanField(default=False, verbose_name='Використовувати в фільтрації товарів в шаблоні')),
                ('filter_type', models.CharField(choices=[('radio', 'Радіокнопка'), ('checkbox', 'Чекбокс')], default='checkbox', max_length=20, verbose_name='Тип фільтра')),
                ('filter_measure', models.CharField(help_text='Одиниця виміру для конкретного фільтра', max_length=50, verbose_name='Одиниця виміру для фільтра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functions.Category', verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeaturesValidators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(max_length=255, null=True, unique=True, verbose_name='Значення характеристики')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functions.Category', verbose_name='Категорія')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_functions.ProductFeatures', verbose_name='Характеристика')),
            ],
        ),
    ]
