# Generated by Django 3.0.8 on 2021-06-02 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Виробник'),
            preserve_default=False,
        ),
    ]
