# Generated by Django 3.0.8 on 2021-05-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertor',
            name='outer_distance_between_bases',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Відстань між лапами, мм'),
        ),
    ]
