# Generated by Django 3.0.8 on 2021-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='invertor_power',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AUX', 'AUX'), ('Cooper&Hunter', 'Cooper&Hunter'), ('Daikin', 'Daikin'), ('Gree', 'Gree'), ('Hitachi', 'Hitachi'), ('Leberg', 'Leberg'), ('LG', 'LG'), ('Mitsubishi Electric', 'Mitsubishi Electric'), ('Mitsubishi Heavy', 'Mitsubishi Heavy'), ('Neoclima', 'Neoclima'), ('Olmo', 'Olmo'), ('Osaka', 'Osaka'), ('Panasonic', 'Panasonic'), ('Samsung', 'Samsung'), ('Smartway', 'Smartway'), ('Toshiba', 'Toshiba')], max_length=255, verbose_name='Бренд'),
        ),
    ]
