# Generated by Django 3.0.8 on 2021-06-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0002_auto_20210609_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='air_consumption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Споживання повітря, м³/год.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('AUX', 'AUX'), ('Cooper&Hunter', 'Cooper&Hunter'), ('Daikin', 'Daikin'), ('Gree', 'Gree'), ('Hitachi', 'Hitachi'), ('Leberg', 'Leberg'), ('LG', 'LG'), ('Mitsubishi Electric', 'Mitsubishi Electric'), ('Mitsubishi Heavy', 'Mitsubishi Heavy'), ('Neoclima', 'Neoclima'), ('Olmo', 'Olmo'), ('Osaka', 'Osaka'), ('Panasonic', 'Panasonic'), ('Samsung', 'Samsung'), ('Smartway', 'Smartway'), ('Toshiba', 'Toshiba')], max_length=255, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cold_efficiency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Продуктивність холод, кВт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cold_watt_consumption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Споживання потужності холод, кВт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cold_work_temratures',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Діапазон роботи на холод,°C'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compressor_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип компресора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dims',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Габаритні розміри, мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_efficiency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Енергоефективність EER/C.O.P.,кВт/кВт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Джерело живлення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фільтр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='freon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фреон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gas_tube_diameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Діаметер газової труби, мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='invertor',
            field=models.CharField(blank=True, choices=[('Так', 'Так'), ('Ні', 'Ні')], max_length=255, null=True, verbose_name='Інвертор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='liquid_tube_diameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Діаметер рідинної труби, мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_magistral_hight_variation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальний перепад висоти магістралі, м'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_magistral_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна довжина магістралі, м'),
        ),
        migrations.AlterField(
            model_name='product',
            name='noise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рівень шуму,дБ(А)(мин/ср/макс)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='outer_dims',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Габаритні розміри, мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='outer_distance_between_bases',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Відстань між лапами, мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='outer_noise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рівень шуму,дБ(А)(мин/ср/макс)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='outer_weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вага, кг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_area',
            field=models.CharField(blank=True, choices=[('до 20', 'до 20'), ('до 25', 'до 25'), ('до 35', 'до 35'), ('до 45', 'до 45'), ('до 50', 'до 50'), ('до 60', 'до 60'), ('до 70', 'до 70'), ('> 70', '> 70')], max_length=255, null=True, verbose_name='Рекомендована площа приміщення, м²'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warm_efficiency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Продуктивність тепло, кВт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warm_watt_consumption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Споживання потужності тепло, кВт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warm_work_temratures',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Діапазон роботи на тепло,°C'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warrant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гарантія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вага, кг'),
        ),
    ]
