# Generated by Django 3.0.8 on 2021-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0003_auto_20210603_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='conditioner_type',
            field=models.CharField(blank=True, choices=[('Настінні спліт-системи', 'Настінні спліт-системи'), ('Мультиспліт-системи', 'Мультиспліт-системи'), ('Мобільні кондиціонери', 'Мобільні кондиціонери'), ('Кондиціонери на стелю', 'Кондиціонери на стелю'), ('Касетні кондиціонери', 'Касетні кондиціонери'), ('Канальні кондиціонери', 'Канальні кондиціонери')], max_length=255, null=True, verbose_name='Тип кондиціонера'),
        ),
    ]
