# Generated by Django 3.0.8 on 2021-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0004_auto_20210603_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recommended_area',
            field=models.CharField(choices=[('до 20', 'до 20'), ('до 25', 'до 25'), ('до 35', 'до 35'), ('до 45', 'до 45'), ('до 50', 'до 50'), ('до 60', 'до 60'), ('до 70', 'до 70'), ('> 70', '> 70')], max_length=255, verbose_name='Рекомендована площа приміщення, м²'),
        ),
    ]
