# Generated by Django 3.0.8 on 2021-06-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0007_product_for_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_main_page',
            field=models.BooleanField(default=False, verbose_name='Показувати на головній'),
        ),
    ]
